add SharedLayout, UserData
fantusya/petly pull request #1
Opened 2023-03-18 11:59 UTC by Antifishka

2023-03-18 19:33 UTC, fantusya requested changes

2023-03-18 19:33 UTC, fantusya commented on src/components/UserData/UserData.jsx
> +  return (
```
<Section>
    <Container>
        <UserText>My information:</UserText>
        <Avatar/>
    </Container>
</Section>
```

Сначала идёт тег section, потом контейнер, потом наполнение.
Тогда после `<UserText>` у тебя будет какой-нибудь `<UserContainer/>` (div), на котором уже будут стили, которые ты прописала для `<Section>`. И уже в этом `<UserContainer/>` будет `<Avatar/>`

2023-03-18 19:33 UTC, fantusya commented on src/components/UserData/UserData.styled.js
> +export const UserText = styled.p`
Лучше назвать компонент UserTitle и сделать тегом h2, так как это заголовок секции

2023-03-18 19:33 UTC, fantusya commented on src/components/UserData/UserData.styled.js
> +export const Avatar = styled.div`
это тег img

2023-03-18 19:33 UTC, fantusya commented on src/components/UserData/UserData.styled.js
> +  margin: 0 auto 12px auto;
Можно сократить до:
margin: 0 auto 12px;

2023-03-18 19:33 UTC, fantusya commented on src/globalStyles/globalStyle.js
> +    background-color: ${p => p.theme.shadows.background};
`background-color: ${p => p.theme.colors.background};`

2023-03-18 21:03 UTC, Antifishka commented on src/components/UserData/UserData.jsx
> +  return (
Сначала обычно идет контейнер потом секция, потому что стили контейнера одинаковіе для всех секций и для всей страницы. Я его вообще на SharedLoyout вешала

2023-03-18 21:06 UTC, Antifishka commented on src/components/UserData/UserData.styled.js
> +export const UserText = styled.p`
+

2023-03-18 21:09 UTC, Antifishka commented on src/components/UserData/UserData.styled.js
> +export const Avatar = styled.div`
сейчас это заглушка div с svg плюсиком, img там бедет по условию, когда будет бэк. Я ж не буду плюсик в img ставить

2023-03-18 21:14 UTC, Antifishka commented on src/components/UserData/UserData.styled.js
> +  margin: 0 auto 12px auto;
+

2023-03-18 21:15 UTC, Antifishka commented on src/globalStyles/globalStyle.js
> +    background-color: ${p => p.theme.shadows.background};
+

2023-03-18 23:31 UTC, fantusya requested changes

2023-03-18 23:31 UTC, fantusya commented on src/components/Logout/Logout.styled.js
> +  height: 22px;
А зачем кнопке высоту задавать? Высота как на макете должна быть за счёт типографии: интерлиньяжа, размера шрифта и его семейства.

2023-03-18 23:31 UTC, fantusya commented on src/components/UserData/UserData.styled.js
> +  line-height: 1.3;
Ставь `line-height: ${p => p.theme.lineHeights.logo};`
На макете вообще 1.8 (но оно встречается только здесь, поэтому создавать отдельное поле для этого в теме, как по мне, странно), но я посмотрела весь макет, и там средние значения 1.375, 1.573 и т.д. 
Так что пусть будет как у logo, 1.5

2023-03-18 23:31 UTC, fantusya commented on src/components/UserData/UserData.styled.js
> +  background-color: transparent;
`background-color: ${p => p.theme.colors.transparent};`

2023-03-18 23:31 UTC, fantusya commented on src/globalStyles/globalStyle.js
> +  max-width: 480px;
удалить `max-width`, потому что оно перекрывает все стили ниже, и ничего не работает

2023-03-18 23:31 UTC, fantusya commented on src/components/UserDataItem/UserDataItem.styled.js
> +`;
```
:not(:last-child) {
    margin-bottom: 12px;
  }
```
замени на `gap: 12px;`

2023-03-18 23:31 UTC, fantusya commented on src/components/UserDataItem/UserDataItem.styled.js
> +`;
добавить `border: ${p => p.theme.borders.normal} ${p => p.theme.colors.transparent};`, чтобы сбросить браузерные стили кнопки

2023-03-19 07:10 UTC, Antifishka commented on src/components/UserData/UserData.jsx
> +  return (
+

2023-03-19 07:18 UTC, Antifishka commented on src/globalStyles/globalStyle.js
> +  max-width: 480px;
ширину на на контейнер ставить на каждый девайс

2023-03-19 07:26 UTC, Antifishka commented on src/components/UserDataItem/UserDataItem.styled.js
> +`;
там нет дисплей флекс колум, я мне нужно растояние по длине между ли задать. Если поставить gap, будет растояние мужду элементами в лишке. Cмотри живую страницу, когда проверяешь

2023-03-19 07:28 UTC, Antifishka commented on src/components/UserDataItem/UserDataItem.styled.js
> +`;
я еще кнопки не закончила

2023-03-19 07:42 UTC, Antifishka commented on src/components/Logout/Logout.styled.js
> +  height: 22px;
+

2023-03-19 12:43 UTC, fantusya approved these changes

2023-03-19 12:43 UTC, merged