Предварительная разметка
fantusya/petly pull request #2
Opened 2023-03-18 21:05 UTC by Hrihor-Dmytro

Привет, набросал предварительно разметку формы регистрации.

2023-03-19 00:08 UTC, fantusya requested changes

2023-03-19 00:08 UTC, fantusya commented on src/pages/LoginPage/LoginPage.jsx
> +          <Error name="email" component="div" />
Я не пробовала, будут ли рисоваться наши ошибки с помощью этого `Error` . 
Я делала через `ErrorMessage` у формика. 
Те строчки, что мы писали в yup ('At least 7 symbols', 'Password is a required field' и т.д.) должны отображаться с помощью компонента ошибки формика, когда мы вводим что-о неправильно.
Если не получится через `Error`, то скажешь мне, я скажу как делать через `ErrorMessage` или почитай доки.

2023-03-19 00:08 UTC, fantusya commented on src/pages/LoginPage/LoginPage.jsx
> +    </div>
Ещё сделай, пожалуйста, отдельным компонентом это:
![Screenshot_7](https://user-images.githubusercontent.com/100998437/226146537-78fff535-d12b-41e0-a686-29f3454f36bb.png)
Чтобы компонент принимал пропс url, и в зависимости от того, какой мы передадим url, туда и будет нас кидать ссылка. Потому что такой же компонент есть в форме регистрации, только он ведёт на твою страницу. А у тебя наоборот.

2023-03-19 22:50 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +  email: yup.string().email('').required(),
+

2023-03-19 22:51 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +    .min(4)
+

2023-03-19 22:51 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +    .max(12)
Ок

2023-03-19 22:51 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +    .min(4)
Ок

2023-03-19 22:51 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +  email: yup.string().email('').required(),
Ок

2023-03-19 22:51 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +      /\+?\d{1,4}?[-.\s]?\(?\d{1,3}?\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,9}/,
Ок

2023-03-19 22:51 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +      'Password is correct'
Ок

2023-03-19 22:51 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +    .required(),
Ок

2023-03-19 22:51 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +const schema = yup.object().shape({
Ок

2023-03-19 22:52 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +    <div>
Ок

2023-03-19 22:52 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +          <Error name="email" component="div" />
Ок

2023-03-19 22:52 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +    </div>
Эту вынес, но что то она мне не очень нравится, завтра еще поюзаю.

2023-03-20 08:56 UTC, fantusya requested changes

2023-03-20 08:56 UTC, fantusya commented on src/helpers/validationSchemas/loginSchema.jsx
> +      / ^(?!.* ).{7,32}$/,
`/^\S+$/
`давай эту регулярку, власть поменялась

2023-03-20 08:56 UTC, fantusya commented on src/pages/LoginPage/LoginPage.jsx
> +    <Box>
`<Box as="section">`

2023-03-20 08:56 UTC, fantusya commented on src/pages/LoginPage/LoginPage.jsx
> +        <Formik
`h1` где?

2023-03-20 08:56 UTC, fantusya commented on src/pages/routeFormLoginRegister.jsx
> +const RouteFormLoginRegister = () => {
`const RouteFormLoginRegister = ({link, question, pageName}) => {`

2023-03-20 09:50 UTC, Hrihor-Dmytro commented on src/helpers/validationSchemas/loginSchema.jsx
> +      / ^(?!.* ).{7,32}$/,
Ок)

2023-03-20 15:42 UTC, Hrihor-Dmytro commented on src/pages/LoginPage/LoginPage.jsx
> +        <Formik
Ух, точно) Сек добавлю

2023-03-20 15:48 UTC, Hrihor-Dmytro commented on src/pages/routeFormLoginRegister.jsx
> +  return (
Ok

2023-03-20 15:48 UTC, Hrihor-Dmytro commented on src/pages/routeFormLoginRegister.jsx
> +    );
Понял

2023-03-20 23:30 UTC, fantusya approved these changes

2023-03-20 23:30 UTC, merged